import { prisma } from '@/lib/prisma'
import { requireWorkspaceRole } from '@/modules/organizations/context'
import { createIntakeTemplateAction } from './actions'

export const dynamic = 'force-dynamic'

export default async function IntakeFormsPage() {
  const context = await requireWorkspaceRole(['OWNER', 'MANAGER'])
  const [templates, offerings] = await Promise.all([
    prisma.intakeTemplate.findMany({ where: { businessId: context.business.id }, include: { Questions: { orderBy: { sortOrder: 'asc' } }, Services: { include: { offering: true } } }, orderBy: { createdAt: 'desc' } }),
    prisma.serviceOffering.findMany({ where: { businessId: context.business.id, active: true }, orderBy: { name: 'asc' } }),
  ])
  return <div className="space-y-8"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-clay-600">Customer preparation</p><h1 className="mt-2 font-display text-4xl text-cocoa-950">Intake forms</h1><p className="mt-2 text-cocoa-600">Create reusable questions for services. Sensitive answers require customer consent and are encrypted.</p></header><section className="grid gap-4 md:grid-cols-2">{templates.map((template) => <article key={template.id} className="rounded-2xl border border-sand-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-clay-600">{template.Services.map((item) => item.offering.name).join(', ')}</p><h2 className="mt-2 font-display text-2xl text-cocoa-950">{template.name}</h2>{template.Questions.map((question) => <div key={question.id} className="mt-3 rounded-xl bg-cream-50 p-3"><p className="font-semibold text-cocoa-900">{question.label}</p><p className="text-xs text-cocoa-600">{question.type.replaceAll('_', ' ')}{question.required ? ' · Required' : ''}{question.sensitive ? ' · Sensitive' : ''}</p></div>)}</article>)}</section><form action={createIntakeTemplateAction} className="space-y-5 rounded-3xl border border-sand-200 bg-white p-6"><div><p className="text-xs font-bold uppercase tracking-wider text-clay-600">New template</p><h2 className="mt-1 font-display text-2xl text-cocoa-950">Add an intake question</h2></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Template name" name="name" /><label className="text-sm font-semibold text-cocoa-800">Service<select required name="offeringId" className="mt-2 min-h-11 w-full rounded-xl border border-sand-300 bg-white px-3"><option value="">Choose service</option>{offerings.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Question" name="label" /><label className="text-sm font-semibold text-cocoa-800">Answer type<select name="type" className="mt-2 min-h-11 w-full rounded-xl border border-sand-300 bg-white px-3"><option value="SHORT_TEXT">Short text</option><option value="LONG_TEXT">Long text</option><option value="SINGLE_CHOICE">Single choice</option><option value="MULTIPLE_CHOICE">Multiple choice</option><option value="YES_NO">Yes / no</option><option value="DATE">Date</option><option value="CONSENT">Required consent</option></select></label><Field label="Choices (comma separated)" name="options" required={false} /></div><div className="flex flex-wrap gap-5 text-sm"><label><input type="checkbox" name="required" className="mr-2" />Required</label><label><input type="checkbox" name="sensitive" className="mr-2" />Sensitive health or personal information</label></div><button className="rounded-full bg-cocoa-900 px-6 py-3 text-sm font-semibold text-white">Create intake template</button></form></div>
}

function Field({ label, name, required = true }: { label: string; name: string; required?: boolean }) { return <label className="text-sm font-semibold text-cocoa-800">{label}<input required={required} name={name} className="mt-2 min-h-11 w-full rounded-xl border border-sand-300 px-3" /></label> }
