'use client'
import { useState } from 'react'
import { WalkInCustomerFields } from './WalkInCustomerFields'
type Option = { id: string; name: string }
export function BookingEditor({ locations, offerings, staff, action }: { locations: Option[]; offerings: Option[]; staff: Option[]; action?: (formData: FormData) => void | Promise<void> }) {
  const [kind, setKind] = useState<'REGISTERED' | 'WALK_IN'>('REGISTERED')
  return <form action={action} className="space-y-5 rounded-3xl border border-sand-200 bg-white p-5 shadow-sm sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-clay-600">New appointment</p><h2 className="mt-1 font-display text-2xl text-cocoa-950">Add a booking</h2></div><fieldset><legend className="mb-2 text-sm font-semibold text-cocoa-800">Customer type</legend><div className="flex flex-wrap gap-4"><label><input type="radio" name="customerKind" value="REGISTERED" checked={kind === 'REGISTERED'} onChange={() => setKind('REGISTERED')} /> Registered customer</label><label><input type="radio" name="customerKind" value="WALK_IN" checked={kind === 'WALK_IN'} onChange={() => setKind('WALK_IN')} /> Walk-in customer</label></div></fieldset>{kind === 'REGISTERED' ? <label className="block text-sm font-semibold text-cocoa-800">Customer ID<input required name="customerId" className="mt-1 w-full rounded-xl border border-sand-300 px-3 py-2" /></label> : <WalkInCustomerFields />}<div className="grid gap-4 sm:grid-cols-2"><Select label="Location" name="locationId" options={locations} /><Select label="Service" name="offeringId" options={offerings} /><Select label="Professional" name="membershipId" options={staff} optional /><label className="text-sm font-semibold text-cocoa-800">Date and time<input required name="startsAt" type="datetime-local" className="mt-1 w-full rounded-xl border border-sand-300 px-3 py-2" /></label></div><button type="submit" className="rounded-full bg-cocoa-900 px-5 py-3 text-sm font-semibold text-white">Create booking</button></form>
}
function Select({ label, name, options, optional = false }: { label: string; name: string; options: Option[]; optional?: boolean }) { return <label className="text-sm font-semibold text-cocoa-800">{label}<select required={!optional} name={name} className="mt-1 w-full rounded-xl border border-sand-300 bg-white px-3 py-2"><option value="">{optional ? 'Unassigned' : `Choose ${label.toLowerCase()}`}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label> }
