import Link from 'next/link'
import { Card } from '@/components/ui/Card'
import type { BusinessOverviewModel } from '@/modules/dashboard/business-overview'

function money(cents: number) {
  return `EC$${(cents / 100).toFixed(2)}`
}

function Metric({ label, value }: { label: string; value: string | number }) {
  return <Card className="p-5"><p className="text-sm text-cocoa-600">{label}</p><p className="mt-2 font-display text-3xl text-cocoa-950">{value}</p></Card>
}

function Alerts({ alerts }: Pick<BusinessOverviewModel, 'alerts'>) {
  if (!alerts.length) return null
  return <section aria-label="Operational alerts" className="rounded-2xl border border-clay-200 bg-clay-50 p-5"><h2 className="font-display text-2xl text-cocoa-950">Needs attention</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-cocoa-700">{alerts.map((alert) => <li key={`${alert.kind}:${alert.message}`}>{alert.message}</li>)}</ul></section>
}

export function WorkspaceOverview({ overview }: { overview: BusinessOverviewModel }) {
  if (overview.role === 'ACCOUNTS') return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-clay-600">Accounts</p><h2 className="mt-2 font-display text-4xl text-cocoa-950">Finance overview</h2><p className="mt-2 text-cocoa-600">Today’s canonical booking and payment-request figures for your authorized locations.</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Booked revenue" value={money(overview.bookedRevenueCents)} /><Metric label="Cash collected" value={money(overview.cashCollectedCents)} /><Metric label="Cash due at appointments" value={money(overview.cashDueAtAppointmentCents)} /><Metric label="Pending online payment" value={money(overview.pendingOnlinePaymentCents)} /></div><Card className="p-5"><p className="font-semibold text-cocoa-950">Cash collection will be available in the Finance workspace.</p><p className="mt-2 text-sm text-cocoa-600">No cash has been recorded here until the audited cash-collection ledger is available.</p></Card><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Recent finance activity</h3><ul className="mt-3 space-y-2 text-sm text-cocoa-700">{overview.recentTransactions.length ? overview.recentTransactions.map((transaction) => <li key={transaction.id}>Booking {transaction.id} · {money(transaction.amountCents)}</li>) : <li>No booked transactions in this period.</li>}</ul></Card><Link href="/business/finance" className="inline-flex rounded-full bg-cocoa-900 px-5 py-3 text-sm font-semibold text-white">Open finance ledger</Link><Alerts alerts={overview.alerts} /></div>

  if (overview.role === 'STAFF') return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-clay-600">My work</p><h2 className="mt-2 font-display text-4xl text-cocoa-950">My schedule overview</h2><p className="mt-2 text-cocoa-600">Your assigned appointments and upcoming time off.</p></header><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Next appointment</h3><p className="mt-2 text-cocoa-700">{overview.nextAppointment ? `${overview.nextAppointment.customerName} · ${overview.nextAppointment.offeringName}` : 'No upcoming assigned appointment.'}</p></Card><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Today’s assigned schedule</h3><p className="mt-2 text-cocoa-700">{overview.todaySchedule.length} appointment{overview.todaySchedule.length === 1 ? '' : 's'} assigned today.</p></Card><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Assigned locations</h3><p className="mt-2 text-cocoa-700">{overview.locations.map((location) => location.name).join(', ') || 'No assigned locations.'}</p></Card><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Upcoming time off</h3><p className="mt-2 text-cocoa-700">{overview.upcomingTimeOff.length ? overview.upcomingTimeOff.map((timeOff) => timeOff.locationName).join(', ') : 'No upcoming time off.'}</p></Card><Link href="/business/schedule" className="inline-flex rounded-full bg-cocoa-900 px-5 py-3 text-sm font-semibold text-white">Open my schedule</Link></div>

  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-clay-600">Operations</p><h2 className="mt-2 font-display text-4xl text-cocoa-950">Operations overview</h2><p className="mt-2 text-cocoa-600">Today’s appointments and operational follow-up for your authorized locations.</p></header><div className="grid gap-4 sm:grid-cols-3"><Metric label="Today’s appointments" value={overview.todayAppointments} /><Metric label="Pending approvals" value={overview.pendingApprovals} /><Metric label="Staff scheduled" value={overview.staffScheduledToday} /></div><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Today’s agenda</h3><ul className="mt-3 space-y-2 text-sm text-cocoa-700">{overview.agenda.length ? overview.agenda.map((appointment) => <li key={appointment.id}>{appointment.customerName} · {appointment.offeringName} · {appointment.locationName}</li>) : <li>No appointments scheduled today.</li>}</ul></Card><Card className="p-5"><h3 className="font-display text-2xl text-cocoa-950">Location utilization</h3><ul className="mt-3 space-y-2 text-sm text-cocoa-700">{overview.locationUtilization.map((location) => <li key={location.locationId}>{location.locationName}: {location.bookedCapacity}/{location.scheduledCapacity || 0} scheduled capacity ({location.percentage}%)</li>)}</ul></Card><Alerts alerts={overview.alerts} /><div className="flex flex-wrap gap-3"><Link href="/business/calendar" className="rounded-full bg-cocoa-900 px-5 py-3 text-sm font-semibold text-white">Open calendar</Link><Link href="/business/team" className="rounded-full border border-sand-300 px-5 py-3 text-sm font-semibold text-cocoa-800">Manage team</Link><Link href="/business/services" className="rounded-full border border-sand-300 px-5 py-3 text-sm font-semibold text-cocoa-800">Manage services</Link></div></div>
}
