import { prisma } from '@/lib/prisma'
import { requireLocationAccess } from '@/modules/organizations/access'

type Interval = [string, string]
type ScheduleInput = { businessId: string; locationId: string; membershipId: string; weekday: number; intervals: Interval[] }
type Dependencies = { authorize(input: ScheduleInput): Promise<unknown>; validateTenantIntegrity(input: ScheduleInput): Promise<unknown>; persist(input: ScheduleInput & { minuteIntervals: Array<[number, number]> }): Promise<unknown> }
const minute = (value: string) => { const match = /^(\d{2}):(\d{2})$/.exec(value); if (!match) throw new Error('INVALID_SCHEDULE'); const result = Number(match[1]) * 60 + Number(match[2]); if (result < 0 || result > 1439) throw new Error('INVALID_SCHEDULE'); return result }
function normalized(intervals: Interval[]) { const values = intervals.map(([start, end]) => [minute(start), minute(end)] as [number, number]).sort((a, b) => a[0] - b[0]); if (values.some(([start, end]) => start >= end)) throw new Error('INVALID_SCHEDULE'); if (values.some((item, index) => index > 0 && item[0] < values[index - 1][1])) throw new Error('OVERLAPPING_SCHEDULE'); return values }
const invalidSchedule = () => Object.assign(new Error('INVALID_SCHEDULE'), { code: 'INVALID_SCHEDULE' })
const defaults: Dependencies = {
  authorize: async (input) => { const access = await requireLocationAccess(input.locationId, ['OWNER', 'MANAGER']); if (access.businessId !== input.businessId) throw invalidSchedule() },
  validateTenantIntegrity: async (input) => {
    const membership = await prisma.businessMembership.findFirst({ where: { id: input.membershipId, businessId: input.businessId, active: true, Locations: { some: { locationId: input.locationId } } }, select: { id: true } })
    if (!membership) throw invalidSchedule()
  },
  persist: (input) => prisma.$transaction(async (tx) => { await tx.staffSchedule.deleteMany({ where: { membershipId: input.membershipId, locationId: input.locationId, weekday: input.weekday } }); return Promise.all(input.minuteIntervals.map(([startMinute, endMinute]) => tx.staffSchedule.create({ data: { membershipId: input.membershipId, locationId: input.locationId, weekday: input.weekday, startMinute, endMinute } }))) }),
}
export async function saveStaffSchedule(input: ScheduleInput, dependencies: Partial<Dependencies> = {}) { if (!Number.isInteger(input.weekday) || input.weekday < 0 || input.weekday > 6) throw invalidSchedule(); const resolved = { ...defaults, ...dependencies }; const minuteIntervals = normalized(input.intervals); await resolved.authorize(input); await resolved.validateTenantIntegrity(input); return resolved.persist({ ...input, minuteIntervals }) }
export async function saveLocationHours(input: Omit<ScheduleInput, 'membershipId'>) { if (!Number.isInteger(input.weekday) || input.weekday < 0 || input.weekday > 6) throw invalidSchedule(); const minuteIntervals = normalized(input.intervals); const access = await requireLocationAccess(input.locationId, ['OWNER', 'MANAGER']); if (access.businessId !== input.businessId) throw invalidSchedule(); return prisma.$transaction(async (tx) => { await tx.locationHours.deleteMany({ where: { locationId: input.locationId, weekday: input.weekday } }); return Promise.all(minuteIntervals.map(([startMinute, endMinute]) => tx.locationHours.create({ data: { locationId: input.locationId, weekday: input.weekday, startMinute, endMinute } }))) }) }
export async function saveTimeOff(input: { businessId?: string; membershipId: string; locationId: string; startsAt: Date; endsAt: Date; reason?: string }) { if (input.startsAt >= input.endsAt) throw new Error('INVALID_TIME_OFF'); const access = await requireLocationAccess(input.locationId, ['OWNER', 'MANAGER']); if (input.businessId && access.businessId !== input.businessId) throw new Error('INVALID_TIME_OFF'); const membership = await prisma.businessMembership.findFirst({ where: { id: input.membershipId, businessId: access.businessId, active: true, Locations: { some: { locationId: input.locationId } } }, select: { id: true } }); if (!membership) throw new Error('INVALID_TIME_OFF'); const { businessId: _businessId, ...data } = input; return prisma.staffTimeOff.create({ data }) }
